export const CHANGE_NUMBER = 'CHANGE_NUMBER';
export const CITY_CHANGE = 'CITY_CHANGE';
export const ANIMAL_CHANGE = 'ANIMAL_CHANGE';
export const DISPLAY_CHANGE = 'DISPLAY_CHANGE';
export const FETCH_START = 'FETCH_START';
export const WEATHER_CHANGE_ERROR = 'WEATHER_CHANGE_ERROR';
export const WEATHER_CHANGE_SUCCESS = 'WEATHER_CHANGE_SUCCESS';

